### PR TITLE
Enabled Direct setup and updated Readme

### PR DESCRIPTION
**Pull request by PrieureDeSion**
Convenience, you see!

### CODE REVIEW

**Comment by nihal111** [comment]
Change `pip install` to `sudo pip install` in all cases

**Comment by nihal111** [comment]
This might not be a good idea as, errors are very frequent while installing. Will test it before merging. I request you to do the same. `pip uninstall` everything and then run this.

**Comment by PrieureDeSion** [comment]
I used this script to install the whole package.

Yes, it must be run as sudo.

**Comment by PrieureDeSion** [comment]
-_-

**Comment by nihal111** [comment]
I'm sorry I forgot about this. So a few minor changes. Do not echo "Successfully Installed" ever. There may be unpredictable errors. As for error management I don't know how we could deal with errors. But I guess there would be a way to check which packages installed and which didn't by checking the output. So **check for packages that don't install correctly and prompt the user regarding those at the end**. Also I apt-get and pip are nice as they don't take time if the packages are already installed. But attempting to install pygame by cloning the hg repo is very time consuming. I would suggest **checking if pygame is already installed before doing it all over again**. Something like asserting `python -c 'import pygame'` returns an error on output, to run installation script fot pygame.

**Comment by nihal111** [comment]
#5 solves this in a better way

**Pull request closed without merging**
